import { EarthTierId, EnemyId, EARTH_TIER_IDS } from './types';

export interface TierVisualStyle {
  tier:EarthTierId;accent:string;accentSoft:string;frameMaterial:string;glow:string;particles:string;badgeStyle:string;revealVFXID:string;
}
const COLORS=[['#73dfff','#153c50'],['#5dffe4','#104c4b'],['#b78cff','#3b2454'],['#e16cff','#521d59'],['#ffcf62','#55351c'],['#ff6c68','#5b1c27'],['#a879ff','#2d174e'],['#5da0ff','#172e65'],['#ff584c','#631a1c'],['#efe6ff','#4b3864'],['#d7ffff','#285e69'],['#f7df87','#28252c']];
export const TIER_VISUAL_STYLES=Object.fromEntries(EARTH_TIER_IDS.map((tier,index)=>[tier,{tier,accent:COLORS[index][0],accentSoft:COLORS[index][1],frameMaterial:index<3?'RIFT_ALLOY':index<7?'ARCANE_CRYSTAL':index<9?'ROYAL_GOLD':index<11?'ASCENDANT_GLASS':'VOID_GOLD',glow:index<4?'SOFT':index<9?'BLOOM':'CELESTIAL',particles:index<3?'SPARK':index<7?'SHARD':index<10?'RUNE':'ORBIT',badgeStyle:index>=11?'SOVEREIGN':index>=7?'ROYAL':'ANGULAR',revealVFXID:`VFX_TIER_${tier}_REVEAL`}])) as Record<EarthTierId,TierVisualStyle>;

export type EnemyRole='NORMAL'|'FAST'|'ARMORED'|'ELITE'|'SHIELDED'|'REGENERATING'|'SUPPORT'|'BOSS';
export interface EnemyVisualProfile { id:string;enemyId:EnemyId;role:EnemyRole;atlasIndex:number;movementAnimation:string;hitVFX:string;deathVFX:string;spawnVFX:string;baseReachVFX:string;visualScale:number;visualFamily:'RIFTBORN';silhouette:string;coreGlow:string; }
export const ENEMY_VISUAL_PROFILES:Record<EnemyId,EnemyVisualProfile>={
  EARTH_GRUNT:{id:'VIS_RIFTBORN_GRUNT',enemyId:'EARTH_GRUNT',role:'NORMAL',atlasIndex:0,movementAnimation:'AGGRESSIVE_RUN',hitVFX:'CORE_FLASH',deathVFX:'RIFT_DISSOLVE',spawnVFX:'RIFT_CRACK',baseReachVFX:'CLAW_SLASH',visualScale:1,visualFamily:'RIFTBORN',silhouette:'BALANCED_BIPED',coreGlow:'CYAN'},
  EARTH_RUNNER:{id:'VIS_RIFTBORN_RUNNER',enemyId:'EARTH_RUNNER',role:'FAST',atlasIndex:1,movementAnimation:'QUADRUPED_DASH',hitVFX:'CORE_FLASH_FAST',deathVFX:'SLIDE_DISSOLVE',spawnVFX:'RIFT_CRACK',baseReachVFX:'ENERGY_LEAP',visualScale:.9,visualFamily:'RIFTBORN',silhouette:'THIN_TRIANGLE',coreGlow:'CYAN'},
  EARTH_TANK:{id:'VIS_RIFTBORN_TANK',enemyId:'EARTH_TANK',role:'ARMORED',atlasIndex:2,movementAnimation:'HEAVY_WALK',hitVFX:'ARMOR_SPARK',deathVFX:'HEAVY_COLLAPSE',spawnVFX:'RIFT_CRACK_HEAVY',baseReachVFX:'HEAVY_SMASH',visualScale:1.55,visualFamily:'RIFTBORN',silhouette:'WIDE_BLOCK',coreGlow:'VIOLET'},
  EARTH_SHIELDED:{id:'VIS_RIFTBORN_SHIELD',enemyId:'EARTH_SHIELDED',role:'SHIELDED',atlasIndex:3,movementAnimation:'CONTROLLED_MARCH',hitVFX:'SHIELD_IMPACT',deathVFX:'BARRIER_SHATTER',spawnVFX:'RIFT_CRACK_HEX',baseReachVFX:'SHIELD_RAM',visualScale:1.25,visualFamily:'RIFTBORN',silhouette:'SYMMETRIC_SHELL',coreGlow:'WHITE_BLUE'},
  EARTH_REGENERATOR:{id:'VIS_RIFTBORN_REGEN',enemyId:'EARTH_REGENERATOR',role:'REGENERATING',atlasIndex:4,movementAnimation:'ORGANIC_CRAWL',hitVFX:'TISSUE_FLASH',deathVFX:'ORGANIC_DISINTEGRATE',spawnVFX:'BIO_RIFT',baseReachVFX:'TENDRIL_STRIKE',visualScale:1.2,visualFamily:'RIFTBORN',silhouette:'TENDRIL_BODY',coreGlow:'GREEN_GOLD'},
  EARTH_SUPPORT:{id:'VIS_RIFTBORN_SUPPORT',enemyId:'EARTH_SUPPORT',role:'SUPPORT',atlasIndex:5,movementAnimation:'HOVER',hitVFX:'RING_FLASH',deathVFX:'RING_EXPLOSION',spawnVFX:'ORBITAL_RIFT',baseReachVFX:'SUPPORT_PULSE',visualScale:1.05,visualFamily:'RIFTBORN',silhouette:'ORBITAL_SMALL',coreGlow:'VIOLET'},
  EARTH_ELITE:{id:'VIS_RIFTBORN_ELITE',enemyId:'EARTH_ELITE',role:'ELITE',atlasIndex:6,movementAnimation:'ELITE_CHARGE',hitVFX:'ELITE_CORE_FLASH',deathVFX:'ELITE_SHARD_BURST',spawnVFX:'ELITE_RIFT',baseReachVFX:'ELITE_IMPACT',visualScale:1.35,visualFamily:'RIFTBORN',silhouette:'HORNED_HALO',coreGlow:'GOLD'},
  EARTH_BOSS:{id:'VIS_RIFTBORN_BOSS',enemyId:'EARTH_BOSS',role:'BOSS',atlasIndex:8,movementAnimation:'DELIBERATE_FLOAT',hitVFX:'BOSS_CORE_FLASH',deathVFX:'BOSS_DIMENSIONAL_COLLAPSE',spawnVFX:'BOSS_RIFT',baseReachVFX:'BOSS_IMPACT',visualScale:3,visualFamily:'RIFTBORN',silhouette:'MAJOR_THREAT',coreGlow:'TIER'},
};

export interface BossVisualProfile {tier:EarthTierId;name:string;atlasIndex:number;hpFrameStyle:string;mechanics:EnemyRole[];phaseVisuals:string[];warningVFX:string;spawnVFX:string;deathVFX:string;}
const BOSS_NAMES=['裂界巨獸','疾界獵獸','紫晶破城獸','界障巨像','不滅裂獸','神墮巨獸','無相裂界者','裂界王獸','赤皇殲界獸','至尊界靈','墮聖界使','帝界終焉獸'];
export const BOSS_VISUAL_PROFILES=Object.fromEntries(EARTH_TIER_IDS.map((tier,index)=>[tier,{tier,name:BOSS_NAMES[index],atlasIndex:8+index,hpFrameStyle:index===11?'VOID_GOLD_ORBITAL':index>=7?'ROYAL_TIER':'STANDARD_TIER',mechanics:index===0?['ARMORED']:index===1?['FAST']:index===2?['ELITE','ARMORED']:index===3?['SHIELDED']:index===4?['REGENERATING']:index===5?['SHIELDED','ELITE']:index===6?['SUPPORT']:index>=9?['ELITE','SHIELDED','REGENERATING']:['ELITE','ARMORED'],phaseVisuals:index===11?['SHELL_CLOSED','VOID_REVEAL','ORBIT_OPEN']:index>=5?['BASE','AWAKENED']:['BASE'],warningVFX:`VFX_BOSS_WARNING_${tier}`,spawnVFX:`VFX_RIFT_SPAWN_${tier}`,deathVFX:index===11?'VFX_SOVEREIGN_DISSOLUTION':'VFX_BOSS_DISSOLVE'}])) as Record<EarthTierId,BossVisualProfile>;
export function tierStyleVars(tier:EarthTierId){const style=TIER_VISUAL_STYLES[tier];return {'--tier-accent':style.accent,'--tier-soft':style.accentSoft} as React.CSSProperties;}
